### ISSUE TITLE
Needs developer tools / switch to work - any chance to bypass this?

### ISSUE THREAD

**Issue by pictosun** [TobiasMende/alfred-audio-switcher#3]
Hi,

actually I really love your extension. But I don't want to install and use switch/python developer tools to get it to work.

Is there any chance to get it working without the need to install this huge developer tools package?

**Comment by TobiasMende** [comment]
Hi @pictosun, thank you for reporting this. I assumed that `/usr/bin/swift` is available by default on Macs these days. This might not be the case, though 🤔 

Which Mac, Mac OS version, and Alfred version are you using?


There might be a solution, but I am not 100% sure yet. – Alfred Workflows also support `/usr/bin/swift` scripts now. Maybe Alfred takes care of installing the requirements, if I use this type of script (currently using `/bin/zsh`, calling a Swift script).

Could you please do me a favor and test this for me? – I have created a small workflow. If it works on your machine, I might be able to convert my workflow to use this approach. [Alfred Swift Test.zip](https://github.com/TobiasMende/alfred-audio-switcher/files/15126294/Alfred.Swift.Test.zip)

Thanks a lot,
Tobi

**Comment by pictosun** [comment]
Hi @TobiasMende 

Thanks for your feedback. I'm using MacBooks M1, M2, M3 (Sonoma 14.4.1), Alfred 5.5 (2257).

When testing your workflow I get this answer. 
<img width="573" alt="SCR-20240427-ixbx" src="https://github.com/TobiasMende/alfred-audio-switcher/assets/55917962/5f2443c1-9fd6-4aca-bc94-39e2640189f4">

**Comment by TobiasMende** [comment]
Hi @pictosun, thanks for sharing. I think we won't get around the need to install Swift (via the developer tools) – I am not aware that apple allows to access the API that I am using for fetching and setting the devices could be used by any other means (like a scripting language).

The other options are: Installing unsigned third party tools or using AppleScript to navigate through the System Settings (if that even is still possible) – Both solutions are not great and also slower than the approach via the native APIs.

I wish to have another answer, but at this point I don't think there is a better option besides installing the developer tools.
