### ISSUE TITLE
Friendly device names?

### ISSUE THREAD

**Issue by iliyang** [TobiasMende/alfred-audio-switcher#6]
Firstly, thank you for this brilliant workflow — super easy to set up and use!!

I wonder, would it be possible to customize the names of the devices? For example I have
- MacBook Pro Speakers
- DELL U2723QE

I'd love it if I could put some friendly names to them, like
- Computer
- Monitor

Is this a feature you'd find useful and consider implementing?

Thanks!

**Comment by TobiasMende** [comment]
Thanks for the inspiration @iliyang – I like this feature idea. I will look into it.

**Comment by TobiasMende** [comment]
I think what we could to is to use the output and input favorites and allow a CSV-style config. We could do:
```
<actual_name>;<friendly_name>
```

Let me give it a try :-)

**Comment by iliyang** [comment]
Amazing — this feature is already out and working perfectly as expected! Thank you so much @TobiasMende 🙏
